baseURL = "http://example.org/"
languageCode = "en-us"
title = "Rox's Webpage"
theme = "chillout"
paginate = 10
# paginatePath = ["pages", "vg-content"]
# pygmentsStyle = "bw"
# pygmentsCodeFences = true
# pygmentsCodeFencesGuessSyntax = true
# enableEmoji = true

[Params]
# colorScheme = "auto"
# hideColorSchemeToggle = false
name = "Rox's Webpage"
author = "RoxNoAnne"
description = "This website has a blog, video game content, and contacts and socials. RoxNoAnne is a person with talents and hobbies such as music, art, programming, and gaming. Rox likes to play around with bugs sometimes. His favorites include moths, praying mantises, and spiders. Below is a page with more information about him. This website may have future updates including Disqus comments or theme changes."
mainSections = ["page", "vg-content", "contact"]

[blackfriday]
extensions = ["hardLineBreak"]

[taxonomies]
author = "author"
categories = "categories"
tags = "tags"
keywords = "keywords"

[[menu.main]]
name = "Blog Page"
weight = 1
url = "pages"

[[menu.main]]
name = "Video Game Content"
weight = 2
url = "vg-content/"

[[menu.main]]
name = "Contact Information"
weight = 3
url = "contact/"
